"""Real Blender material failure/retry with an existing generated PNG.

Isolated data and registry, read-only existing runtime. Host control is a fixture.
Fault injection changes the first worker binding target only, never the durable
submitted request. No image generation is run here: previously generated bytes
are imported once and reused. This is not installed Host/browser acceptance.
"""
from __future__ import annotations

import argparse
import asyncio
import hashlib
import importlib.util
import json
from pathlib import Path
import time
from typing import Any

from mediaforge.asset_import import import_image_asset
from mediaforge.blender_runtime import BlenderRuntimeResolver
from mediaforge.config import REPOSITORY_ROOT
from mediaforge.host.client import HostIdentity
from mediaforge.scene_recipe_jobs import SceneRecipeJobManager
from mediaforge.scene_recipes import SceneCreateRequest, SceneMaterialRequest
from mediaforge.scene_workspace import SceneWorkspace
from mediaforge.store import Store


class FailFirstMaterial(SceneWorkspace):
    material_calls = 0

    async def _material_operation(self, *args: Any, **kwargs: Any) -> Any:
        if kwargs.get("action") == "apply":
            self.material_calls += 1
            if self.material_calls == 1:
                kwargs["binding"] = kwargs["binding"].model_copy(update={"object_name": "missing-fault-target"})
        return await super()._material_operation(*args, **kwargs)


def snapshot(store: Store, workspace: SceneWorkspace, scene_id: str) -> dict:
    scene, revisions = workspace.catalog.get("user:7", scene_id)
    return {"scene": scene.model_dump(mode="json"),
        "revisions": [r.model_dump(mode="json") for r in revisions],
        "assets": {a.id: {"metadata": a.model_dump(mode="json"),
            "sha256": hashlib.sha256(store.asset_path(a.id).read_bytes()).hexdigest(),
            "provenance": store.get_provenance(a.id).model_dump(mode="json")}
            for a in store.list_assets()}}


async def execute(store: Store, workspace: FailFirstMaterial, host: Any, texture_id: str) -> dict:
    host.proceed.set()
    identity = HostIdentity(authorization="Bearer fixture-only", addon_id="media-forge",
        subject="job:material-retry-parent", actor_subject="user:7", expires_at=int(time.time()) + 600,
        granted_capabilities=frozenset({"jobs.write"}))
    manager = SceneRecipeJobManager(store, workspace, host)
    evidence: dict = {}
    try:
        request = SceneCreateRequest.model_validate({"name": "Material retry acceptance cube", "recipe": {"operations": [
            {"type": "primitive.add", "object_id": "cube", "name": "Cube", "primitive": "cube", "dimensions": [1, 1, 1]},
            {"type": "material.set", "object_id": "cube", "base_color": [0.5, 0.5, 0.5, 1]},
            {"type": "uv.smart_project", "object_id": "cube"}]}})
        shape, _ = await manager.submit(request, identity)
        await manager.wait_cleanup(shape.id, timeout=60)
        created = await asyncio.to_thread(manager.projection, shape.id, "user:7")
        assert created["status"] == "succeeded", created["error"]
        scene_id = created["result"]["scene"]["id"]
        before = await asyncio.to_thread(snapshot, store, workspace, scene_id)
        before_jobs = {j.id: j.model_dump(mode="json") for j in await asyncio.to_thread(store.list_jobs)}
        material = SceneMaterialRequest.model_validate({"scene_id": scene_id, "binding": {
            "source_revision_id": created["result"]["revision"]["id"], "image_asset_id": texture_id,
            "object_name": "Cube", "material_slot": 0, "channel": "base_color", "uv_map": "UVMap"}})
        first, _ = await manager.submit(material, identity)
        await manager.wait_cleanup(first.id, timeout=60)
        failed = await asyncio.to_thread(manager.projection, first.id, "user:7")
        # Blender may exit zero after a Python exception; missing trusted result
        # is still rejected by the independent result validator.
        assert failed["status"] == "failed" and failed["error"]["code"] == "scene_material_worker_invalid", failed
        assert not failed["asset_ids"]
        assert await asyncio.to_thread(snapshot, store, workspace, scene_id) == before
        await manager.stop()
        manager = SceneRecipeJobManager(store, workspace, host)
        retry, record = await manager.submit(material.model_copy(update={"retry_job_id": first.id}),
                                            identity, retry_of=first.id)
        await manager.wait_cleanup(retry.id, timeout=60)
        result = await asyncio.to_thread(manager.projection, retry.id, "user:7")
        assert result["status"] == "succeeded", result["error"]
        assert result["retry_of"] == first.id and result["input_sha256"] == failed["input_sha256"]
        after = await asyncio.to_thread(snapshot, store, workspace, scene_id)
        assert len(after["revisions"]) == 2 and after["revisions"][0] == before["revisions"][0]
        assert all(after["assets"][key] == value for key, value in before["assets"].items())
        assert set(after["assets"]) - set(before["assets"]) == set(result["asset_ids"])
        assert len(result["asset_ids"]) == 2 and workspace.material_calls == 2
        revision = after["revisions"][-1]
        assert any(d["asset_id"] == texture_id and d["sha256"] == before["assets"][texture_id]["sha256"]
                   for d in revision["dependencies"])
        assert all(a["metadata"]["sha256"] == a["sha256"] for a in after["assets"].values())
        assert workspace.resolver.live_reference_count(record.runtime_id) == 0
        working = await asyncio.to_thread(store.list_scene_working_copies, "user:7")
        assert not [w for w in working if w.state == "active"]
        assert await asyncio.to_thread(lambda: not list(workspace.material_root.iterdir()))
        jobs = await asyncio.to_thread(store.list_jobs)
        assert not [j for j in jobs if j.request.operation in {"image.generate", "image.edit"}]
        after_jobs = {j.id: j.model_dump(mode="json") for j in jobs}
        assert all(after_jobs[key] == value for key, value in before_jobs.items())
        assert set(after_jobs) - set(before_jobs) == {first.id, retry.id}
        evidence.update(shape=created, failed=failed, retry=result, scene_id=scene_id,
            existing_assets_unchanged=True, successful_jobs_unchanged=True,
            failed_head_unchanged=True, revision_count=2,
            new_assets=2, material_worker_attempts=2, image_generation_jobs=0,
            runtime_references=0, active_working_copies=0, material_staging_empty=True,
            before=before, after=after, passed=True)
        return evidence
    finally:
        await manager.stop()


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--evidence-dir", type=Path, required=True)
    parser.add_argument("--managed-root", type=Path, required=True)
    parser.add_argument("--image", type=Path, required=True)
    parser.add_argument("--image-sha256", required=True)
    args = parser.parse_args()
    content = args.image.read_bytes()
    assert hashlib.sha256(content).hexdigest() == args.image_sha256
    args.evidence_dir.mkdir(mode=0o700, parents=True, exist_ok=False)
    started = time.monotonic()
    resolver = BlenderRuntimeResolver(registry_path=args.evidence_dir / "registry/blender-runtimes.json",
        managed_root=args.managed_root, legacy_root=args.evidence_dir / "absent-legacy",
        manifest_path=REPOSITORY_ROOT / "config/blender-runtime.json",
        catalog_path=REPOSITORY_ROOT / "config/blender-runtime-catalog.json",
        trusted_worker=REPOSITORY_ROOT / "worker_packs/blender/compile_asset.py")
    spec = json.loads((REPOSITORY_ROOT / "config/blender-runtime.json").read_text())
    runtime_id = "blender-4.5.9-linux-x64"
    resolver.register_managed(runtime_id=runtime_id, version=spec["version"], location=runtime_id,
                              archive_sha256=spec["archive_sha256"])
    resolver.activate(runtime_id)
    store = Store(args.evidence_dir / "data")
    store.initialize()
    image = import_image_asset(store, content, purpose="source")
    workspace = FailFirstMaterial(store, resolver, REPOSITORY_ROOT / "worker_packs/blender/scene_document.py",
        recipe_worker=REPOSITORY_ROOT / "worker_packs/blender/scene_recipe.py",
        material_worker=REPOSITORY_ROOT / "worker_packs/blender/material_binding.py")
    workspace.initialize()
    helper_spec = importlib.util.spec_from_file_location("pin_fixture", Path(__file__).with_name("3ds_recipe_runtime_pin_e2e.py"))
    assert helper_spec and helper_spec.loader
    helpers = importlib.util.module_from_spec(helper_spec)
    helper_spec.loader.exec_module(helpers)
    evidence: dict = {"mode": "source_real_blender_material_worker_fault_host_fixture",
        "input_image_sha256": args.image_sha256, "imported_image_id": image.id,
        "not_tested": ["installed Host", "HTTP/browser", "image generation during this run", "signed release"]}
    try:
        evidence.update(asyncio.run(execute(store, workspace, helpers.DelayedHost(), image.id)))
    finally:
        evidence["elapsed_sec"] = round(time.monotonic() - started, 3)
        (args.evidence_dir / "observations.json").write_text(json.dumps(evidence, indent=2) + "\n")
        print(json.dumps({k: v for k, v in evidence.items() if k not in {"before", "after", "shape", "failed", "retry"}}), flush=True)


if __name__ == "__main__":
    main()
